convert = {
    "ajg" : "anjing", "anjg" : "anjing",
    "og" : "orang",
    "amat" : "sangat",
    "bangt" : "sangat",
    "ngamoknya" : "ngamuknya",
    "baklan" : "bakalan",
    "sbnrnya" : "sebenarnya",
    "cobak" : "coba",
    "blm" : "belum",
    "bln" : "bulan",
    "bnr" : "benar", "bener" : "benar",
    "bgst" : "bangsat",
    "fak" : "fuck",
    "gblk" : "goblok",
    "gini" : "begini",
    "ga" : "tidak", "gak" : "tidak",
    "gw" : "gue", "gua": "gue", "gwe": "gue", "gye": "gue",
    "ijin": "izin",
    "iy" : "iya", "y" : "iya",
    "kaga" : "kagak",
    "kalo" : "kalau", "kl" : "kalau",
    "kontwol": "kontol", "kntl": "kontol",
    "lu" : "lo",
    "lbh" : "lebih",
    "maen" : "main",
    "mnyt" : "monyet", "nyet": "monyet",
    "pake" : "pakai",
    "pduli" : "peduli",
    "puny" : "punya",
    "sampe" : "sampai",
    "saha" : "siapa",
    "smal" : "small",
    "smw" : "semua",
    "syirik" : "sirik",
    "tae" : "tai", "taek" : "tai",
    "tot" : "ngentot",
    "udh" : "udah",
    "ny" : "nya",
    "yg" : "yang",
    "dtng" : "dateng",
    "prg" : "pergi",
    "sya" : "saya",
    "dging" : "daging",
    "sia" : "kamu",
    "dr" : "dari",
    "kasi" : "kasih",
    "blio" : "beliau",
    "ak" : "aku",
    "sm" : "sama",
    "doanb" : "doang",
    "kmu" : "kamu",
    "tu" : "itu",
    "tp" : "tapi",
    "taik" : "tai",
    "kapir" : "kafir",
    "emg" : "memang",
    "bgt" : "banget",
    "ril" : "real",
    "lngsng" : "langsung",
    "pokonnya" : "pokoknya",
    "bg" : "bang",
    "smua" : "semua",
    "natamu" : "matamu",
    "lg" : "lagi",
    "dri" : "dari",
    "jgn" : "jangan", "jan" : "jangan",
    "mw" : "mau",
    "jlek" : "jelek",
    "badjingan" : "bajingan",
    "tul" : "betul",
    "dh" : "dah",
    "merkosa" : "perkosa",
    "balikin" : "kembalikan",
    "comel" : "lucu",
    "edan" : "gila",
    "kya" : "kayak",
    "pdhl" : "padahal",
    "bkn" : "bukan",
    "dgr" : "dengar",
    "ttp" : "tetap",
    "lgi" : "lagi",
    "trakhir" : "terakhir",
    "ap" : "apa",
    "badjingan" : "bajingan",
    "smpe" : "sampai",
    "cwe" : "cewe",
    "perfom" : "perform",
    "gk" : "engga",
    "wes" : "sudah",
    "klo" : "kalau",
    "rmh" : "rumah",
    "blg" : "bilang",
    "kurg" : "kurang",
    "blgnya" : "bilangnya",
    "bhkn" : "bahkan",
    "kayknya" : "kayaknya",
    "mnta" : "minta",
    "org" : "orang",
    "dibyr" : "dibayar",
    "dah" : "sudah", "udah" : "sudah",
    "kek" : "kayak",
    "tuh" : "itu",
    "jg" : "juga",
    "jdi" : "jadi", "jd" : "jadi",
    "bngt" : "banget",
    "amp" : "sampai",
    "mingu" : "minggu",
    "nungu" : "menunggu",
    "kyk" : "kayak",
    "utk" : "untuk",
    "dg" : "dengan",
    "maf" : "maaf",
    "mo" : "mau",
    "trus" : "terus",
    "tingal" : "tinggal",
    "inget" : "ingat",
    "krn" : "karena",
    "emng" : "memang",
    "dpt" : "dapat",
    "gt" : "begitu",
    "sat" : "bangsat",
    "ntar" : "sebentar",
    "dlu" : "dulu",
    "anj" : "anjing",
    "woy" : "woi",
    "nder" : "sender",
    "hapy" : "happy",
    "eror" : "error",
    "ningalin" : "meninggalkan",
    "ngak" : "tidak",
    "skrg" : "sekarang",
    "tdk" : "tidak",
    "sdh" : "sudah",
    "thn" : "tahun",
    "skrng" : "sekarang",
    "loe" : "lu",
    "sbg" : "sebagai",
}