convert = {
    "ajg" : "anjing","anjg" : "anjing", "og" : "orang", 
    "amat" : "sangat", "bangt" : "sangat",
    "ngamoknya" : "ngamuknya",
    "baklan" : "bakalan",
    "sbnrnya" : "sebenarnya",
    "cobak" : "coba",
    
    "blm" : "belum",
    "bln" : "bulan",
    "bnr" : "benar", "bener" : "benar",
    "bgst" : "bangsat",
    "fak" : "fuck",
    "gblk" : "goblok",
    "gini" : "begini",
    "ga" : "tidak", "gak" : "tidak",
    "gw" : "gue", "gua": "gue", "gwe": "gue", "gye": "gue",
    "ijin": "izin",
    "iy" : "iya", "y" : "iya",
    "kaga" : "kagak",
    "kalo" : "kalau", "kl" : "kalau",
    "kontwol": "kontol", "kntl": "kontol",
    "lu" : "lo",
    "lbh" : "lebih",
    "maen" : "main",
    "mnyt" : "monyet", "nyet": "monyet",
    "pake" : "pakai",
    "pduli" : "peduli",
    "puny" : "punya",
    "sampe" : "sampai",
    "saha" : "siapa",
    "smal" : "small",
    "smw" : "semua",
    "syirik" : "sirik",
    "tae" : "tai", "taek" : "tai",
    "tot" : "ngentot",
    "udh" : "udah",
    "ny" : "nya",
    "yg" : "yang",
    "dtng" : "dateng",
    "prg" : "pergi",
    "sya" : "saya",
    "dging" : "daging",
    "sia" : "kamu",
    "dr" : "dari",
    "kasi" : "kasih",
    "blio" : "beliau",
    "ak" : "aku",
    "sm" : "sama",
    "doanb" : "doang",
    "kmu" : "kamu",
    "tu" : "itu",
    "tp" : "tapi",
    "taik" : "tai",
    "kapir" : "kafir",
    "emg" : "memang",
    "bgt" : "banget",
    "ril" : "real",
    "lngsng" : "langsung",
    "pokonnya" : "pokoknya",
    "bg" : "bang",
    "smua" : "semua",
    "natamu" : "matamu",
    "lg" : "lagi",
    "dri" : "dari",
    "jgn" : "jangan",
    "mw" : "mau",
    "jlek" : "jelek",
    "badjingan" : "bajingan",
    "tul" : "betul",
    "dh" : "dah",
    "merkosa" : "perkosa",
    "balikin" : "kembalikan",
    "comel" : "lucu",
    "edan" : "gila",
    "kya" : "kayak",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
}